name: Add codesandbox link

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: ["blog-site-carousel"]
  pull_request_target:
    types: [opened, edited, synchronize]
    branches: ["blog-site-carousel"]

jobs:
  codesandbox-comment:
    permissions: write-all
    name: Add codesandbox link comment
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            You can check this code at CodeSandbox with the link
            https://githubbox.com/${{ github.repository }}/tree/${{ github.head_ref }}
