name: PR Sanity Check

on:
  push:
    branches: ["blog-site"]
  pull_request:
    branches: ["blog-site"]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages
        run: |
          npm install

      - name: Lint check
        run: |
          npm run lint:fix
